root: true
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
env:
  node: true
  jest: true
rules:
  no-console: warn
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/explicit-function-return-type': warn
  eqeqeq:
    - error
    - always
globals: {}
